In [2]:
import numpy as np

In [8]:
scalar = np.array(20)
print(scalar)
scalar.ndim

20


0

In [9]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [13]:
tensor = np.array([[[1,2,3],[4,5,6]], [[1,3,4],[6,6,7]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 3 4]
  [6 6 7]]]


3

## Para agregar o eliminar dimensiones usar: 

In [7]:
multi = np.array([1,2,3], ndmin = 10)
print(multi)
multi.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [6]:
expand = np.expand_dims(np.array([1,2,3]), axis=1) #aquí agrega columnas
expand = np.expand_dims(expand, axis=0) # aquí agrega filas
expand

array([[[1],
        [2],
        [3]]])

In [10]:
## para eliminar dimensiones que no se están utilizando:

multi_1 = np.squeeze(multi)
print(multi_1, multi)

[1 2 3] [[[[[[[[[[1 2 3]]]]]]]]]]
