In [19]:
import numpy as np

In [3]:
##para crear listas de np usar arange

np.arange(0,20,2) #Esto crea un array de cero a veinte con saltos de dos.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
##Recordad que si pones varios números dentro de los argumentos de la función se crearán distintas dimensiones
zeros = np.zeros(5)
ones = np.ones(5)
print(zeros, ones)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [17]:
zeros = np.zeros((4,4))
ones = np.ones([4,4])
print(zeros,"\n\n", ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
identidad = np.eye(4)
identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#  inicio, final, n_datos
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [44]:
#genera un valor aleatorio
np.random.rand()

0.07432925865701279

In [45]:
#genera un array con valores aleatorios
np.random.rand(4)

array([0.92491279, 0.39906457, 0.81779921, 0.54526017])

In [60]:
#genera una matriz con valores aleatorios
np.random.rand(4,4)

array([[0.33224684, 0.88456577, 0.80034749, 0.31672619],
       [0.00210963, 0.63580087, 0.48801631, 0.32964559],
       [0.1190361 , 0.73335803, 0.90446094, 0.86194009],
       [0.91072026, 0.22186523, 0.88718605, 0.6630141 ]])

In [72]:
#genera un valor aleatorio entre cero y diez.
np.random.randint(0,10)

8

In [73]:
#genera una matriz con valores aleatorios entre cero y diez
np.random.randint(0,10,[4,5])

array([[9, 0, 0, 1, 4],
       [0, 5, 5, 6, 0],
       [4, 3, 9, 7, 1],
       [4, 8, 0, 2, 4]])