In [2]:
import numpy as np

### Shape and Reshape sirve para ver la forma del arreglo/matriz/tensor

In [11]:
rand = np.random.randint(1,5,6)
rand

array([4, 1, 3, 1, 2, 2])

In [18]:
rand = rand.reshape([3,2])
print(rand,"\n\n", rand.shape)

[[4 1]
 [3 1]
 [2 2]] 

 (3, 2)


In [19]:
rand = np.reshape(rand, [3,2])
print(rand,"\n\n", rand.shape)

[[4 1]
 [3 1]
 [2 2]] 

 (3, 2)


In [26]:
np.reshape(rand, [1,6], 'F')

array([[4, 3, 2, 1, 1, 2]])

In [27]:
np.reshape(rand, [1,6], 'C')

array([[4, 1, 3, 1, 2, 2]])

#### The parameter C and F is for the organization of the data in the array, use "C" for C programing language arrays, and F for Fortran language.