In [1]:
import numpy as np

In [17]:
matriz = np.random.randint(1, 20, (2,5))
matriz

array([[14, 11, 15, 10, 12],
       [ 6, 18, 14, 12, 16]])

In [22]:
#encuentra el valor maximo de todas las dimensiones.
matriz.max()


18

In [23]:
#regresa el valor maximo de cada  fila
matriz.max(1)

array([15, 18])

In [24]:
#El valor maximo de cada columna
matriz.max(0)

array([14, 18, 15, 12, 16])

In [25]:
#indice del valo maximo de la matriz
matriz.argmax()

6

In [28]:
#tambien funciona para filas y columnas
print(matriz.argmax(0))
print(matriz.argmax(1))

[0 1 0 1 1]
[2 1]


In [33]:
#aplica las mismas funciones de max pero para min

print(matriz.min())
print(matriz.min(1))
print(matriz.min(0), "\n")

print(matriz.argmin(0))
print(matriz.argmin(1))

6
[10  6]
[ 6 11 14 10 12] 

[1 0 1 0 0]
[3 0]


In [34]:
matriz.ptp() #matriz.max() - matriz.min()  peak to peak

12

In [42]:
arr = matriz.reshape((1,10))
arr

array([[14, 11, 15, 10, 12,  6, 18, 14, 12, 16]])

In [44]:
#Esta es la mediana (el numero en el 50%)
np.percentile(arr, 50)

#tambien puedes aplicar median en lugar del percentile
np.median(arr)
arr

13.0

In [50]:
#para sacar la media
arr.mean()

#también puedes aplicar la media por filas y columnas
arr.mean(1)
arr.mean(0)

12.8

In [47]:
arr.sort()# para acomodar de menor a mayor
arr

array([[ 6, 10, 11, 12, 12, 14, 14, 15, 16, 18]])

In [48]:
np.std(arr) #desviación estandar

3.2186953878862163

In [49]:
np.var(arr) #varianza

10.36

#A continuación ingreso la función para unir distintos arreglos.

In [54]:
a = np.array(([1,2,3],[4,5,6]), ndmin=2)
b = np.array([7,8,9])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b = np.expand_dims(b, axis=0)
b

array([[7, 8, 9]])

In [35]:
b.ndim

2

Para hacer una concatenación antes hay que tener el mismo numero de dimensiones

In [41]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
np.concatenate((a,b.T), axis=1)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3