In [2]:
import numpy as np

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr_copy = arr[0:6]
arr_copy

array([0, 1, 2, 3, 4, 5])

In [7]:
arr_copy[:] = 0
arr_copy

array([0, 0, 0, 0, 0, 0])

In [8]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr[0:6].copy()

In [15]:
arr_copy[:] = 100

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr_copy

array([100, 100, 100, 100, 100, 100])

arreglos diferentes, no misma direccion en memoria