In [1]:
import numpy as np

In [13]:
con = np.linspace(1,10,10, dtype='int8')
con

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
con>5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
operable = con>5
con[operable]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
con[con>5]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [15]:
con[(con>5) & (con<8)]

array([6, 7], dtype=int8)

In [17]:
con[con>7] = 100
con

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100], dtype=int8)

In [18]:
con[con == 100] = 0
con

array([1, 2, 3, 4, 5, 6, 7, 0, 0, 0], dtype=int8)

In [116]:
arr = np.random.randint(1,10,[1000])
arr = arr[arr==2]
np.size(arr)

103