In [1]:
import numpy as np

In [2]:
# Esto no es lo que esperamos
lista = [1,2]
lista * 2

[1, 2, 1, 2]

In [10]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1/arr2

/tmp/ipykernel_479/1672552411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr2 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr2 + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr2 - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
rand = np.random.randint(1,20,(20, 10))
rand

array([[ 5,  2, 11, 15, 15,  3, 16, 18,  4,  5],
       [ 1, 16, 16,  6, 10, 15,  9, 19, 19, 15],
       [ 6,  4, 19, 10, 10, 18, 18, 12, 14,  5],
       [16, 17,  3, 18,  7,  1, 16, 17,  8,  1],
       [ 3,  3,  2, 15, 14,  4, 18, 13, 14,  2],
       [19, 11, 18,  3, 12, 11,  1, 15, 19,  4],
       [ 1, 18,  5,  6,  3,  3,  4, 10, 15,  4],
       [10, 19, 17,  4, 16,  3, 19, 17, 19, 19],
       [13,  4, 14,  9,  4,  6,  8,  4,  7, 15],
       [ 9, 15, 12,  7,  8,  3,  2, 18,  1, 16],
       [15,  3,  4, 10,  7, 16,  5, 13, 18,  6],
       [ 9, 19, 12, 13,  1, 11, 14,  5,  7,  4],
       [ 6, 17,  1,  4, 18,  5,  7, 12, 18,  8],
       [16, 10, 14,  4,  1, 12,  8,  4, 10, 19],
       [19,  5, 17, 16,  2, 11, 11,  4, 19, 14],
       [10,  2, 12,  9,  1,  3,  4,  3, 18, 11],
       [12,  9, 13,  5,  7, 13,  3,  5, 19,  8],
       [ 4, 10,  1, 13, 10, 12,  6, 11,  7, 12],
       [ 6,  2, 10, 18, 12,  5, 13, 18,  4,  4],
       [ 7,  9,  6, 11,  6, 18,  9, 16, 12,  7]])

In [33]:
rand2 = rand.copy()
rand - rand2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
#Producto punto con la matriz y su transpuesta
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [31]:
#Otra manera de hacer el producto punto
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [38]:
np.zeros((10,10), dtype='int8')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)